### ISSUE TITLE
pypi version isn't updated

### ISSUE THREAD

**Issue by yanirmr** [catalpa-cl/inceptalytics#18]
Hi,

Thank you for this helpful package!
While I used your source code from this repo, I did not encounter any issues. However, now I tried to move the dashboard I built to a more public area, and I find that the PyPI version of the package is outdated. Can you upgrade the PyPI, please?

Thanks!

**Comment by simulacrum6** [comment]
Hi, sure, I will update the pypi package tomorrow.

**Comment by simulacrum6** [comment]
Newest version is now on pypi.
