### ISSUE TITLE
The permissions that "from_remote" method needs

### ISSUE THREAD

**Issue by yanirmr** [catalpa-cl/inceptalytics#20]
Hello,

Please accept my sincere thanks once again for this excellent Python package. After exploring the INCEpTION API further, I have come to the conclusion that the user's permissions need to be clarified:

According to my understanding (through trial and error), if you want to use "from_remote", the user must have the roles "ROLE_USER" and "ROLE_REMOTE" and be a project manager (curator or annotator permissions are not sufficient).
[users permissions' guide](https://inception-project.github.io/releases/24.3/docs/user-guide.html#users_in_getting_started)

**Comment by simulacrum6** [comment]
Hi,

yes, this is correct. There is a [section in the INCEpTION Admin Guide](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/view/INCEpTION/job/INCEpTION%20main/de.tudarmstadt.ukp.inception.app$inception-app-webapp/doclinks/2/#sect_remote_api) specifying this as well.
I will update the docstring of `from_remote` with an explicit list of requirements for this to work.

Thanks!

**Comment by yanirmr** [comment]
I'm glad to help.

It is important to note that defining roles is not enough. The project setting should also grant "manager" rights.
