### ISSUE TITLE
add documentation.

### ISSUE THREAD

**Issue by simulacrum6** [catalpa-cl/inceptalytics#8]
Currently there is no external documentation for the package api. All api functions have a docstring though. There are plenty of automatic documentation tools to create a documentation from those.

Docstrings should probably be extended to also include usage examples.

- [ ] Add tool for automatic documentation generation.
- [ ] Extend API docstrings to contain a clear explanation, argument descriptions and usage examples.

**Comment by zahertalab** [comment]
Hi

Let me make a try.

**Comment by simulacrum6** [comment]
Hey, thanks for your offer! What did you have in mind? The automatic documentation tool or working on the docstrings?

**Comment by zahertalab** [comment]
I'm thinking of automatic documentation tools right now. Have you some of them?

**Comment by simulacrum6** [comment]
Okay, cool. 

There are some out there. [Sphinx](https://www.sphinx-doc.org/) is pretty common. It generates documentation from docstrings and the output can be integrated with [readthedocs](https://readthedocs.org/) and [setuptools](en/master/usage/advanced/setuptools.html) (which we use for building the project).

So if you want to integrate Sphinx, you are more than welcome.

**Comment by zahertalab** [comment]
Ok, this is my first time to corporate. I'm just seeing how to use Github. For your issue, where I can start? [setuptools](https://github.com/ltl-ude/inceptalytics/issues/en/master/usage/advanced/setuptools.html) give me 404!

**Comment by simulacrum6** [comment]
Fork the repository and read up on how to set up Sphinx and then generate the Documentation using that tool. When you have a working solution, create a pull request.
Don't worry about the rest for now.

**Comment by zahertalab** [comment]
Yes, thank you. I'm learning about them for the last few days. And I hope to start soon. Thanks for your patience!

**Comment by AbuTuraab** [comment]
Hi there, let me help you with your documentation.

**Comment by zahertalab** [comment]
OK. Now, where to find the package api?

**Comment by zesch** [comment]
What do you mean?

**Comment by zahertalab** [comment]
> Currently there is no external documentation for the **package ap**i. All api functions have a docstring though. There are plenty of automatic documentation tools to create a documentation from those.

I mean this

**Comment by zesch** [comment]
https://github.com/ltl-ude/inceptalytics/blob/main/inceptalytics/analytics.py
